{% set name = "gwpopulation" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gwpopulation-{{ version }}.tar.gz
  sha256: 1008c3733b96c8bf5f645e27134eb8ae8ca04c7f5deeeac1ff6f5965c5331c06

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - astropy
    - bilby
    - numpy
    - python >=3.8
    - scipy
    - cached_interpolate

test:
  imports:
    - gwpopulation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ColmTalbot/gwpopulation
  summary: Unified population inference
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ColmTalbot
