{% set name = "gwpopulation" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gwpopulation-{{ version }}.tar.gz
  sha256: 401cef5bf19fccc06e07195d12108dedf6f1cdf031dfb1eae602917a337f7d2a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - astropy
    - bilby >=2.2.0
    - numpy
    - python >=3.8
    - scipy
    - cached_interpolate

test:
  requires:
    - pip
    - pytest
  source_files:
    - priors/
    - test/
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show gwpopulation
    # run test suite
    - python -m pytest -ra test/

about:
  home: https://github.com/ColmTalbot/gwpopulation
  summary: Unified population inference
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ColmTalbot
