{% set name = "gwpopulation" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gwpopulation-{{ version }}.tar.gz
  sha256: fc997f8afd8d5356fbbb87611c2ce4db30d7a38ef87a48adca936dbee331bfde

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - astropy
    - bilby >=2.2.0
    - numpy
    - python >=3.8
    - scipy
    - cached_interpolate

test:
  requires:
    - pip
    - pytest
    - jax
    - numpyro
  source_files:
    - priors/
    - test/
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show gwpopulation
    # run test suite
    - python -m pytest -ra test/

about:
  home: https://github.com/ColmTalbot/gwpopulation
  summary: Unified population inference
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ColmTalbot
