{% set name = "gwpopulation" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gwpopulation-{{ version }}.tar.gz
  sha256: 3887b008aa579bd20c79e97297d2d13874cee7daee271aa10a5904b321a6e57c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - astropy
    - bilby
    - numpy
    - python >=3.8
    - scipy

test:
  imports:
    - gwpopulation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ColmTalbot/gwpopulation
  summary: Unified population inference
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ColmTalbot
