{% set name = "gwpopulation" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gwpopulation-{{ version }}.tar.gz
  sha256: 61c49b755a0ee798df530fc77dc891c1439fd066c447d4ef9e31608f1b8627b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - astropy
    - bilby
    - future
    - numpy
    - python >=3.8
    - scipy

test:
  imports:
    - gwpopulation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ColmTalbot/gwpopulation
  summary: Unified population inference
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ColmTalbot
